### PR TITLE
fix: respect directory separator when matching entries

### LINKED ISSUE #213: Incorrect inferred entries from `package.json`
### Environment

Node: v16.14.0
unbuild: v1.1.1

### Reproduction

```sh
git clone https://github.com/Bernankez/unbuild-infer-entries.git
pnpm i
pnpm build
```

### Describe the bug

In `package.json`, it exports
```json
{
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      "import": "./dist/index.mjs"
    },
    "./loader": {
      "require": "./dist/loader.cjs",
      "import": "./dist/loader.mjs"
    },
    "./demo-loader": "./dist/demo-loader.cjs"
  },
}
```
But in the final build file, only `demo-loader` and `index` are preset, and I have no `entries` in my unbuild config.
dist
I think the `loader` was overridden by `demo-loader`.

### Additional context

_No response_

### Logs

```sh
i Automatically detected entries: src/index, src/demo-loader [esm] [cjs]
i Building unbuild-inter-entries
√ Build succeeded for unbuild-inter-entries
  dist/index.cjs (size: 62 B, exports: index)
  dist/demo-loader.cjs (size: 83 B, exports: demoLoader)
  dist/index.mjs (size: 42 B, exports: index)
  dist/demo-loader.mjs (size: 58 B, exports: demoLoader)
Σ Total dist size (byte size): 245 B
```

### PR DESCRIPTION
**Pull request by Bernankez**
fix #213

### CODE REVIEW

**Comment by Bernankez** [comment]
I'm not sure if it's the right way to fix it.

File: src/auto.ts [hunk 1]
```diff
@@ -125,9 +125,9 @@ export function inferEntries(
       if (source) {
         return source;
       }
-      const SOURCE_RE = new RegExp(`${d}${isDir ? "" : "\\.\\w+"}$`);
+      const SOURCE_RE = new RegExp(`/(${d}${isDir ? "" : "\\.\\w+"})$`);
```
Comment (danielroe) [inline src/auto.ts:128]:
```suggestion
      const SOURCE_RE = new RegExp(`(?<=\\\\|/|$)${d}${isDir ? "" : "\\.\\w+"}$`);
```

**Review by danielroe — COMMENTED** [review]
Nice spot! ❤️ I think we likely also want to include files not prefixed with `/` (in case they are at root level), but that is a minor change.

**Review by danielroe — APPROVED** [review]
