### PR TITLE
fix: match least-nested files first when inferring entry

### LINKED ISSUE #107: Wrong entry inference with nested index.ts
Reproducable with https://github.com/unjs/h3/tree/e77679d9ee675555333faa975242713711b1a6ed

src/event/index is automatically infered instead of src/index

### PR DESCRIPTION
**Pull request by danielroe**
resolves  #107

### CODE REVIEW

**Comment by pi0** [comment]
ci seems broken

File: src/auto.ts [hunk 1]
```diff
@@ -114,7 +117,7 @@ export function inferEntries (pkg: PackageJson, sourceFiles: string[]): InferEnt
 
     if (isDir) {
       entry.outDir = outputSlug
-      ;(entry as MkdistBuildEntry).format = output.type
+        ; (entry as MkdistBuildEntry).format = output.type
```
Comment (danielroe) [inline src/auto.ts:120]:
```suggestion
      ;(entry as MkdistBuildEntry).format = output.type
```
