### PR TITLE
fix(esbuild): apply minify with corresponding loader

### LINKED ISSUE #46: minify support
> Maybe we can support min flag for unbuild and unify tooling?

see https://github.com/nuxt-community/color-mode-module/pull/118#discussion_r796728630

### PR DESCRIPTION
**Pull request by SukkaW**
Currently, unbuild's built-in esbuild plugin does support modification (through `rollup.esbuild.minify`). Somehow in some projects, typescript files get passed to esbuild during the esbuild plugin's `renderChunk` phase, causing https://github.com/unjs/unbuild/issues/46#issuecomment-1237575944. The PR fixes that.

### CODE REVIEW

File: src/builder/plugins/esbuild.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ export function esbuild(options: Options): Plugin {
     },
 
     async renderChunk(code, { fileName }) {
-      if (options.minify && !fileName.endsWith(".d.ts")) {
+      if (options.minify && fileName.endsWith(".js")) {
```
Comment (danielroe) [inline src/builder/plugins/esbuild.ts:98]: Should we also include .mjs/.cjs?

**Review by pi0 — APPROVED** [review]
