### PR TITLE
fix: filter commonjs plugin when generating declaration

### LINKED ISSUE #135: Commonjs plugin is run on typescript definition files
Using `import type { WithRequired } from '@apollo/utils.withrequired'` in a file that is processed with `unbuild` yields the following error:
```
Error building /workspaces/apollo-server-integration-h3: SyntaxError: Unexpected token (1:8) in /workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+utils.withrequired@1.0.1/node_modules/@apollo/utils.withrequired/dist/index.d.ts
SyntaxError: Unexpected token (1:8) in /workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+utils.withrequired@1.0.1/node_modules/@apollo/utils.withrequired/dist/index.d.ts
    at pp$4.raise (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:19861:13)
    at pp$9.unexpected (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17162:8)
    at pp$9.semicolon (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17139:66)
    at pp$8.parseExpressionStatement (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17622:8)
    at pp$8.parseStatement (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17355:24)
    at pp$8.parseTopLevel (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17219:21)
    at Parser.parse (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:16991:15)
    at Function.parse (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:17041:35)
    at Graph.contextParse (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/rollup@3.2.2/node_modules/rollup/dist/es/shared/rollup.js:23356:38)
    at tryParse (file:///workspaces/apollo-server-integration-h3/node_modules/.pnpm/@rollup+plugin-commonjs@23.0.0_rollup@3.2.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:17:12) {
  pos: 8,
  loc: {
    column: 8,
    file: '/workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+utils.withrequired@1.0.1/node_modules/@apollo/utils.withrequired/dist/index.d.ts',
    line: 1
  },
  raisedAt: 12,
  frame: '1: declare type WithRequired<T, K extends keyof T> = T & Required<Pick<T, K>>;\n' +
    '           ^\n' +
    '2: export = WithRequired;\n' +
    '3: //# sourceMappingURL=index.d.ts.map',
  id: '/workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+utils.withrequired@1.0.1/node_modules/@apollo/utils.withrequired/dist/index.d.ts',
  hook: 'resolveId',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  watchFiles: [
    '/workspaces/apollo-server-integration-h3/src/index.ts',
    '/workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+utils.withrequired@1.0.1/node_modules/@apollo/utils.withrequired/dist/index.d.ts'
  ]
}
```

I think the issue lies in https://github.com/unjs/unbuild/blob/da197ec7c8e4b1706241bc4785700ef7027e2448/src/builder/rollup.ts#L237-L240, which runs the commonjs also on typescript definition files (and mjs, which seems to be wrong as well).

Reproduction: https://github.com/apollo-server-integrations/apollo-server-integration-h3/pull/12

### LINKED ISSUE #396: commonjs plugin should not include .ts extension
### Environment

node 20

### Reproduction

no

### Describe the bug

in /src/builder/rollup.ts file, commonjs should not include .ts extension, is that expected?
image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kricsleo**
resolves #396
resolves #135

The rollup-plugin-dts conflicts with @rollup/plugin-commonjs:

> The plugin does its own import resolution through the typescript compiler, and usage together with other resolution plugins, such as node-resolve can lead to errors and is not recommended.
> [rollup-plugin-dts - what-to-expect](https://github.com/Swatinem/rollup-plugin-dts?tab=readme-ov-file#what-to-expect)

I'm not sure if it's okay to simply remove @rollup/plugin-commonjs when generating declarations. 🤔 
I've tested some common cases, and it's working fine.

### CODE REVIEW

File: src/builders/rollup/build.ts [hunk 1]
```diff
@@ -83,7 +83,15 @@ export async function rollupBuild(ctx: BuildContext): Promise<void> {
...
       ctx.options.rollup.emitCJS && fixCJSExportTypePlugin(),
-    ].filter(Boolean);
+    ].filter(
+      (plugin) =>
+        /**
+         * Issue: #396
+         * rollup-plugin-dts conflicts with rollup-plugin-commonjs:
+         * https://github.com/Swatinem/rollup-plugin-dts?tab=readme-ov-file#what-to-expect
+         */
+        plugin && (!("name" in plugin) || plugin.name !== "commonjs"),
```
Comment (pi0) [inline src/builders/rollup/build.ts:93]: Why we need to _also_ filter plugins without name here?

Comment (kricsleo) [reply src/builders/rollup/build.ts:93]: I think you might have misunderstood. It means plugins with either _"no name"_ or _"a name, but the name is not equal to 'commonjs'"_ are kept.

(I'm not using `plugin?.name !== "commonjs"` because that would cause a ts error 😅)

**Review by pi0 — APPROVED** [review]
